name = "TOPSolverDemo"
uuid = "d012e6f5-20e1-456b-8591-d3b37621b5f0"
authors = ["Teobaldo Bulh√µes <tbulhoes@ci.ufpb.br>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
VrpSolver = "74f9703e-84bc-48c1-adfc-4da7b8ffac08"

[compat]
ArgParse = "1.2.0"
HiGHS = "1.20.1"
JuMP = "1.29.1"
VrpSolver = "0.1.0"
